services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  minio:
    image: 'minio/minio:latest'
    environment:
      - 'MINIO_ROOT_USER=minioadmin'
      - 'MINIO_ROOT_PASSWORD=minioadmin'
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data

  # imgproxy:
  #   image: darthsim/imgproxy:latest
  #   environment:
  #     - IMGPROXY_KEY=... # ключи безопасности
  #     - IMGPROXY_SALT=...
  #     # Этим ты говоришь, что картинки брать из MinIO (S3)
  #     - IMGPROXY_USE_S3=true
  #     - IMGPROXY_S3_ENDPOINT=http://minio:9000
  #   ports:
  #     - "8080:8080"

  #keycloak:
  #  image: 'quay.io/keycloak/keycloak:latest'
  #  environment:
  #    - 'KEYCLOAK_ADMIN=admin'
  #    - 'KEYCLOAK_ADMIN_PASSWORD=admin'
  #  command: start-dev
  #  ports:
  #    - '8080:8080'

volumes:
  minio_data:
