services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=comics-db'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres_data:/var/lib/postgresql

  minio:
    image: 'minio/minio:latest'
    environment:
      - 'MINIO_ROOT_USER=minioadmin'
      - 'MINIO_ROOT_PASSWORD=minioadmin'
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data

  # imgproxy:
  #   image: darthsim/imgproxy:latest
  #   environment:
  #     - IMGPROXY_KEY=... # ключи безопасности
  #     - IMGPROXY_SALT=...
  #     # Этим ты говоришь, что картинки брать из MinIO (S3)
  #     - IMGPROXY_USE_S3=true
  #     - IMGPROXY_S3_ENDPOINT=http://minio:9000
  #   ports:
  #     - "8080:8080"

  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    environment:
      # Base configuration
      - 'KC_BOOTSTRAP_ADMIN_USERNAME=admin'
      - 'KC_BOOTSTRAP_ADMIN_PASSWORD=admin'
      - 'KC_HTTP_PORT=8081'
      # Database configuration
      - 'KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak'
      - 'KC_DB=postgres'
      - 'KC_DB_USERNAME=myuser'
      - 'KC_DB_PASSWORD=secret'
    command: start-dev
    ports:
      - '8081:8081'
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  postgres_data:
  minio_data:
  keycloak_data:
